// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AssetDistribution asset distribution
// swagger:model AssetDistribution
type AssetDistribution struct {

	// has next
	// Required: true
	HasNext *bool `json:"hasNext"`

	// last
	// Required: true
	Last *string `json:"last"`

	// map of assetId <-> balance
	// Required: true
	Values map[string]int64 `json:"values"`
}

// Validate validates this asset distribution
func (m *AssetDistribution) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHasNext(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLast(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValues(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AssetDistribution) validateHasNext(formats strfmt.Registry) error {

	if err := validate.Required("hasNext", "body", m.HasNext); err != nil {
		return err
	}

	return nil
}

func (m *AssetDistribution) validateLast(formats strfmt.Registry) error {

	if err := validate.Required("last", "body", m.Last); err != nil {
		return err
	}

	return nil
}

func (m *AssetDistribution) validateValues(formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *AssetDistribution) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AssetDistribution) UnmarshalBinary(b []byte) error {
	var res AssetDistribution
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
