// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Block block
// swagger:model Block
type Block struct {

	// blocksize
	// Required: true
	Blocksize *int32 `json:"blocksize"`

	// desired reward
	DesiredReward int64 `json:"desiredReward,omitempty"`

	// features
	Features []int32 `json:"features"`

	// generator
	// Required: true
	Generator *string `json:"generator"`

	// height
	// Required: true
	Height *int32 `json:"height"`

	// nxt consensus
	// Required: true
	NxtConsensus *BlockNxtConsensus `json:"nxt-consensus"`

	// reference
	// Required: true
	Reference *string `json:"reference"`

	// reward
	Reward int64 `json:"reward,omitempty"`

	// signature
	// Required: true
	Signature *string `json:"signature"`

	// timestamp
	// Required: true
	Timestamp *int64 `json:"timestamp"`

	// total fee
	// Required: true
	TotalFee *int32 `json:"totalFee"`

	// transaction count
	// Required: true
	TransactionCount *int32 `json:"transactionCount"`

	// transactions
	// Required: true
	Transactions []Transaction `json:"transactions"`

	// version
	// Required: true
	Version *int32 `json:"version"`
}

// Validate validates this block
func (m *Block) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBlocksize(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGenerator(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHeight(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNxtConsensus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReference(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSignature(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalFee(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransactionCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransactions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Block) validateBlocksize(formats strfmt.Registry) error {

	if err := validate.Required("blocksize", "body", m.Blocksize); err != nil {
		return err
	}

	return nil
}

func (m *Block) validateGenerator(formats strfmt.Registry) error {

	if err := validate.Required("generator", "body", m.Generator); err != nil {
		return err
	}

	return nil
}

func (m *Block) validateHeight(formats strfmt.Registry) error {

	if err := validate.Required("height", "body", m.Height); err != nil {
		return err
	}

	return nil
}

func (m *Block) validateNxtConsensus(formats strfmt.Registry) error {

	if err := validate.Required("nxt-consensus", "body", m.NxtConsensus); err != nil {
		return err
	}

	if m.NxtConsensus != nil {
		if err := m.NxtConsensus.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("nxt-consensus")
			}
			return err
		}
	}

	return nil
}

func (m *Block) validateReference(formats strfmt.Registry) error {

	if err := validate.Required("reference", "body", m.Reference); err != nil {
		return err
	}

	return nil
}

func (m *Block) validateSignature(formats strfmt.Registry) error {

	if err := validate.Required("signature", "body", m.Signature); err != nil {
		return err
	}

	return nil
}

func (m *Block) validateTimestamp(formats strfmt.Registry) error {

	if err := validate.Required("timestamp", "body", m.Timestamp); err != nil {
		return err
	}

	return nil
}

func (m *Block) validateTotalFee(formats strfmt.Registry) error {

	if err := validate.Required("totalFee", "body", m.TotalFee); err != nil {
		return err
	}

	return nil
}

func (m *Block) validateTransactionCount(formats strfmt.Registry) error {

	if err := validate.Required("transactionCount", "body", m.TransactionCount); err != nil {
		return err
	}

	return nil
}

func (m *Block) validateTransactions(formats strfmt.Registry) error {

	if err := validate.Required("transactions", "body", m.Transactions); err != nil {
		return err
	}

	for i := 0; i < len(m.Transactions); i++ {

		if err := m.Transactions[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("transactions" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

func (m *Block) validateVersion(formats strfmt.Registry) error {

	if err := validate.Required("version", "body", m.Version); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Block) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Block) UnmarshalBinary(b []byte) error {
	var res Block
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// BlockNxtConsensus block nxt consensus
// swagger:model BlockNxtConsensus
type BlockNxtConsensus struct {

	// base target
	// Required: true
	BaseTarget *int64 `json:"base-target"`

	// generation signature
	// Required: true
	GenerationSignature *string `json:"generation-signature"`
}

// Validate validates this block nxt consensus
func (m *BlockNxtConsensus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBaseTarget(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGenerationSignature(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BlockNxtConsensus) validateBaseTarget(formats strfmt.Registry) error {

	if err := validate.Required("nxt-consensus"+"."+"base-target", "body", m.BaseTarget); err != nil {
		return err
	}

	return nil
}

func (m *BlockNxtConsensus) validateGenerationSignature(formats strfmt.Registry) error {

	if err := validate.Required("nxt-consensus"+"."+"generation-signature", "body", m.GenerationSignature); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BlockNxtConsensus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BlockNxtConsensus) UnmarshalBinary(b []byte) error {
	var res BlockNxtConsensus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
