// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Signed signed
// swagger:model Signed
type Signed struct {

	// plain text
	Message string `json:"message,omitempty"`

	// Base58-encoded public key
	PublicKey string `json:"publicKey,omitempty"`

	// Base58-encoded signature
	Signature string `json:"signature,omitempty"`
}

// Validate validates this signed
func (m *Signed) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Signed) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Signed) UnmarshalBinary(b []byte) error {
	var res Signed
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
