// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Transaction Transaction's json representation (see https://docs.wavesplatform.com/en/blockchain/transaction/)
// swagger:model Transaction
type Transaction map[string]interface{}

// Validate validates this transaction
func (m Transaction) Validate(formats strfmt.Registry) error {
	return nil
}
